web:
  build: .
  ports:
    - "8080:80"
  volumes:
    - .:/home/app/webapp
  volumes_from:
    - gems
  env_file:
    - ../../env.list
  container_name: www.bedwars.network-${RAILS_ENV}
gems:
  image: busybox
  volumes:
    - /ruby_gems